### ISSUE TITLE
[FEATURE] Ignore path

### ISSUE THREAD

**Issue by SonGokussj4** [Moosync/Moosync#152] opened 2022-10-26 08:09 UTC
**Is your feature request related to a problem? Please describe.**
Hi. Trying Moosync for the first time (liking it so far) and there is one thing I would like to do but can't (or I'm blind :-))
I would like to add my music folder but select few subfolders where I have audiobooks to not be in the list of music.

**Describe the solution you'd like**
Settings -> Paths -> Song DIrectories -> Add Ignored Folder...

**Describe alternatives you've considered**
Of course, moving songs/music I don't want to another directory.
But that doesn't solve a general problem.

**Additional context**
/

Anyway, great job!

**Comment by Ovenoboyo** [comment] 2022-10-26 08:41
This makes sense and it shouldn't be too difficult to implement. I'll look at what I can do. Also glad you liked it :)

**Comment by Ovenoboyo** [comment] 2022-10-26 18:52
So instead of adding a separate section for ignored directories, I've made it such that If you add a directory in the "Song directories" section and then uncheck it, it will work as if its been ignored.

In your case, you'll simply have to add your audio book folder to the list and uncheck it. 

This feature will be available from the next update, however if you don't want to wait, you could use the build from [Github actions](https://github.com/Moosync/Moosync/actions/runs/3329288869). The downloads can be found at the bottom of that page [You'll need to be logged in to download].

Please do let me know if it does not work as intended.

**Comment by SonGokussj4** [comment] 2022-10-26 19:02
Wou, you are fast :-)

I will try that tomorrow and let you know. From what I read, I'm not sure if it will be understood by people at the first glance. If I need to add ignored repository, why would there be a list of combined checked and unchecked paths. 

If I saw that for the first time, I would say "okay, add `[x] dirA`, `[x] dirB` and for now, have in the list `[ ] dirC`, which I will check and add sometimes in the future.

Some kind of icon like ➕ for including and ➖ for ignoring would be more clear in my opinion.
**But** i didn't see the change yet so I'll let you know tomorrow. :-)

**Comment by Ovenoboyo** [comment] 2022-10-26 19:24
> Wou, you are fast :-)
> 
> I will try that tomorrow and let you know. From what I read, I'm not sure if it will be understood by people at the first glance. If I need to add ignored repository, why would there be a list of combined checked and unchecked paths.
> 
> If I saw that for the first time, I would say "okay, add `[x] dirA`, `[x] dirB` and for now, have in the list `[ ] dirC`, which I will check and add sometimes in the future.
> 
> Some kind of icon like ➕ for including and ➖ for ignoring would be more clear in my opinion. **But** i didn't see the change yet so I'll let you know tomorrow. :-)

This does make sense. Maybe its better to keep a separate list for ignored folders for clarity (Or different icons as you suggested). I'll make the suggested changes before the next release.

**Comment by SonGokussj4** [comment] 2022-10-26 19:36
You have an awesome attitude.

I've found three more cosmetic details in the first minutes of trying it. 
Should I create an issue for each or have one issue with a short list.

**Comment by Ovenoboyo** [comment] 2022-10-26 21:02
> You have an awesome attitude.
> 
> I've found three more cosmetic details in the first minutes of trying it. Should I create an issue for each or have one issue with a short list.

Thanks I really appreciate your kind words. Also feel free to open up separate issues or a single combined one your wish. I'll work on them as I get time

**Comment by SonGokussj4** [comment] 2022-10-27 07:42
> Thanks I really appreciate your kind words. Also feel free to open up separate issues or a single combined one your wish. I'll work on them as I get time

I've added some issues that stroke me immediately, hope they help.

#### On another note (not sure where else can I write this)
I totally love your **Settings -> Logs**.
It looks beautiful, it works, search is awesome, you can select level, see the colors, just wow. 
No digging in log files. This is really great.

**Comment by SonGokussj4** [comment] 2022-11-04 13:57
Hi, so I tried newest v6.0.0 and it works well for songs. But still in Albums.

My process

- clean DB at `~/.config/Moosync/Databases/*`
- open Moosync
- go to settings, add folder with all music
- click on `refresh`, this loaded all songs
- add ignored folder
- go to songs: ignored are not there
- go to albums: ignored are still there

**Comment by Ovenoboyo** [comment] 2022-11-04 14:37
@SonGokussj4 Do those albums contain any songs or are they empty?

**Comment by SonGokussj4** [comment] 2022-11-04 14:48
They are empty.

**Comment by Ovenoboyo** [comment] 2023-01-02 10:47
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.

**Closed by Ovenoboyo** 2023-01-02 10:47 UTC
Labels: enhancement
