### ISSUE TITLE
[BUG] Performance issues, freezing, and missing album artwork when playing local music files

### ISSUE THREAD

**Issue by mathe00** [Moosync/Moosync#247] opened 2023-06-19 17:37 UTC
**Describe the bug**

I am reporting an issue related to playing local music files on the Moosync application. Whenever I try to play music from my local storage, it not only slows down the application but also freezes it, rendering it unresponsive.

Furthermore, during the import process, no album artwork for local files appears in the app.

**To Reproduce**

1. Open the Moosync application on my device.
2. Navigate to the music player section.
3. Select a music file stored locally on my device.
4. Observe the application's performance slowdown.
5. Notice that the application eventually freezes and becomes unresponsive.
6. Verify that there is no sound output from the selected music file.

**Expected behavior**
I expect the Moosync application to smoothly play the selected music files without significantly impacting the overall performance. The application should not freeze or become unresponsive during music playback. Furthermore, the music should be audible without any issues.

- OS: Linux Mint
- Version v8.1.1

**Additional context**
After attempting to play a local music file again, the Moosync application has completely ceased to function, rendering it unresponsive and forcing me to terminate the app.

**Comment by Ovenoboyo** [comment] 2023-07-02 21:36
Hey sorry for the late reply. It seems that the performance issues are being caused by the local file scanner. A quick fix would be disabling the scanner by  going into settings > paths and setting the scan interval to -1.

I'm working on a fix for these issues in the time being.

**Comment by Ovenoboyo** [comment] 2023-07-21 08:06
Hi, sorry for the delay but this should be fixed in v9.0.0+. I'm closing this issue since it seems to be fixed, feel free to open it if you feel otherwise :)

**Closed by Ovenoboyo** 2023-07-21 08:06 UTC
Labels: bug

**Comment by Darktowertr** [comment] 2024-04-15 22:31
The update did not solve the problem. The method you suggested in the comment above fixes the sound distortions.
