### ISSUE TITLE
spotify login nothappening properly 

### ISSUE THREAD

**Issue by guri123buri321** [Moosync/Moosync#313] opened 2024-01-01 12:55 UTC
the website to whic hwe are redirected to as we clivck on login shows this 
`INVALID_CLIENT: Invalid redirect URI
        

- OS: garuda linux 
- Version  10.2.0-1

**Comment by Ovenoboyo** [comment] 2024-01-08 12:54
Seems like a duplicate of #116. Can you try the solution provided there?

**Closed by Ovenoboyo** 2024-01-08 12:54 UTC
Labels: bug
