### ISSUE TITLE
[BUG] Many tracks cause app to lag out and use lots of resources

### ISSUE THREAD

**Issue by DrachenfeuerHD** [Moosync/Moosync#185] opened 2022-12-15 20:59 UTC
**Describe the bug**
The App has many lags, uses much memory & cpu when playing many tracks. I am playing an 3k tracks playlist and its using 1gb memory and around 5-20% cpu.

**To Reproduce**
Simply play any playlist with a large number of tracks

**Expected behavior**
I would love the app to preload only the tracks it will play in the near future. This would prevent lagging (the app) and using much resources.

**Screenshots**

- OS: Linux
- Version 5.1.0

**Comment by Ovenoboyo** [comment] 2022-12-16 00:02
Thanks for reporting. I'll definitely look into this

**Comment by DrachenfeuerHD** [comment] 2022-12-16 13:57
Now after a reboot i tried opening the app but i cant use it at all. It tries to load the massive playlist and i cant stop it. So it is stuck in a loading cycle and i cant remove the songs (because its stuck in a massive lag)

**Comment by Ovenoboyo** [comment] 2022-12-16 20:49
Oh thats problematic. If you want to clear all data you can head over to ```~/.config/moosync``` and delete ```config.json``` present there. or if you're on flatpak you can head over to ```~/.var/app/app.moosync.moosync/config/moosync``` to find ```config.json```

**Comment by Ovenoboyo** [comment] 2022-12-17 00:34
I think the reason the app was lagging for you was probably cause the queue was trying to render all songs all at once (even if they weren't visible to you on the screen). A single queue item doesn't require a lot of memory but when all 2000 of them were being rendered at once, it amounted to a fairly huge amount which is why I believe the app was going over 1gigs in memory usage. A small change in any value was also causing the whole queue to be re-rendered which is probably why your CPU usage was very high.

As for the preload behavior, the app will only try to preload the next song when there's around 15secs left for your current song to end. Preload does not work for Youtube embeds, HLS streams and Dash streams. I believe it will also not preload the entire song but only first few chunks of it so you don't have to worry about network wastage over preload.

I've tried to optimize it a bit (and I really hope it works) but I haven't had a chance to try it out properly since my music library is pretty small. If its possible for you, could you get a build from https://github.com/Moosync/Moosync/actions/runs/3717393738 (You'll have to be logged in to Github to be able to download) and try to run it?

**Comment by DrachenfeuerHD** [comment] 2022-12-17 07:31
Yes it fixed the specific problem. But right after i had another problem. It kept spamming "Added 0 tracks" for an infinite tiime until i restarted. The restart however wont make my pc lag out now.

What i did: Added the playlist with 4k songs (I used this one as an example https://www.youtube.com/playlist?list=PLOOhO4UWS_3BYGzgVe8xVgATEfjomqVOC&cbrd=1) as an playlist from URL.
Then i tried playing it, shuffled it 1-2 times and skipped a song. This caused those messages to be spammed.

This is the resource usage now:

![image](https://user-images.githubusercontent.com/35228631/208230961-97781d42-9755-4c67-a055-0aa30b98d786.png)

Also when i am adding those songs i get a lot of those messages:

![image](https://user-images.githubusercontent.com/35228631/208230984-e7e9657c-80f9-484b-ac70-3bb70f555d8d.png)

Now after i cleared the queue & readded i cant reproduce the 0 tracks added message.

After clearing the queue i also get this error message:

![image](https://user-images.githubusercontent.com/35228631/208231031-b25e82a1-fb96-4b69-a3f5-66f0204aeeb8.png)


I've used the .AppImage for testing this one from your https://github.com/Moosync/Moosync/actions/runs/3717393738 build.

**Comment by Ovenoboyo** [comment] 2022-12-17 10:57
Thanks for the playlist link and resource usage details. It seems like you have multiple instances of moosync running. I guess there should be at most 11 processes running if you have hardware acceleration enabled.

I'll try to reproduce the infinite 0 tracks added message. And don't worry about the last error, it doesn't seem too critical but I'll be sure to fix it

**Comment by Ovenoboyo** [comment] 2023-01-02 10:48
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.

**Closed by Ovenoboyo** 2023-01-02 10:48 UTC
Labels: bug
